function [fitresult, gof] = createFit_q1(t_data_steps, q1_data_steps)
%CREATEFIT1(T_DATA_STEPS,Q1_DATA_STEPS)
%  Create a fit.
%
%  Data for 'q1_fit' fit:
%      X Input : t_data_steps
%      Y Output: q1_data_steps
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Sep-2018 14:54:41


%% Fit: 'q1_fit'.
[xData, yData] = prepareCurveData( t_data_steps, q1_data_steps );

% Set up fittype and options.
ft = fittype( 'sin5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [0.0582337661615818 6.28318530717959 0.739579550815066 0.0218964388412988 18.8495559215388 -1.31134684196024 0.0108574787677863 0.20943951023932 0.00468045531905369 0.00482063090460015 31.4159265358979 -2.16847305286288 0.00460824649885664 0.418879020478639 1.58015695523609];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'q1_fit' );
h = plot( fitresult, xData, yData );
legend( h, 'q1_data_steps vs. t_data_steps', 'q1_fit', 'Location', 'NorthEast' );
% Label axes
xlabel t_data_steps
ylabel q1_data_steps
grid on


