    function [fitresult, gof] = createFit(t_cftool, q1)
%CREATEFIT(T_CFTOOL,Q1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t_cftool
%      Y Output: q1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Sep-2018 13:27:35


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t_cftool, q1 );

% Set up fittype and options.
ft = fittype( 'sin6' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [0.0587676746343936 6.28318530717959 0.752435692385334 0.0217941426589277 18.8495559215388 -1.31186715710644 0.0109614767862143 1.5707963267949 0.0323866286393501 0.00480478801995179 31.4159265358979 -2.17633352130864 0.00465966971879497 3.14159265358979 1.63549951482068 0.000685761690385287 25.1327412287183 0.183318587742426];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'q1 vs. t_cftool', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t_cftool
ylabel q1
grid on


